package org.domain.scrum.entity;

// Generated 12/04/2012 11:02:58 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Equipe generated by hbm2java
 */
@Entity
@Table(name = "equipe", catalog = "scrum")
public class Equipe implements java.io.Serializable {

	private Integer idEquipe;
	private String nome;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Sprint> sprints = new HashSet<Sprint>(0);
	private Set<Sprint> sprints_1 = new HashSet<Sprint>(0);
	private Set<Projeto> projetos = new HashSet<Projeto>(0);
	private Set<Projeto> projetos_1 = new HashSet<Projeto>(0);
	private Set<Usuario> usuarios_1 = new HashSet<Usuario>(0);

	public Equipe() {
	}

	public Equipe(String nome) {
		this.nome = nome;
	}

	public Equipe(String nome, Set<Usuario> usuarios, Set<Sprint> sprints,
			Set<Sprint> sprints_1, Set<Projeto> projetos,
			Set<Projeto> projetos_1, Set<Usuario> usuarios_1) {
		this.nome = nome;
		this.usuarios = usuarios;
		this.sprints = sprints;
		this.sprints_1 = sprints_1;
		this.projetos = projetos;
		this.projetos_1 = projetos_1;
		this.usuarios_1 = usuarios_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_equipe", unique = true, nullable = false)
	public Integer getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(Integer idEquipe) {
		this.idEquipe = idEquipe;
	}

	@Column(name = "nome", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	public Set<Sprint> getSprints() {
		return this.sprints;
	}

	public void setSprints(Set<Sprint> sprints) {
		this.sprints = sprints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	public Set<Sprint> getSprints_1() {
		return this.sprints_1;
	}

	public void setSprints_1(Set<Sprint> sprints_1) {
		this.sprints_1 = sprints_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	public Set<Projeto> getProjetos() {
		return this.projetos;
	}

	public void setProjetos(Set<Projeto> projetos) {
		this.projetos = projetos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	public Set<Projeto> getProjetos_1() {
		return this.projetos_1;
	}

	public void setProjetos_1(Set<Projeto> projetos_1) {
		this.projetos_1 = projetos_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	public Set<Usuario> getUsuarios_1() {
		return this.usuarios_1;
	}

	public void setUsuarios_1(Set<Usuario> usuarios_1) {
		this.usuarios_1 = usuarios_1;
	}

}
