package org.domain.scrum.entity;

// Generated 12/04/2012 11:02:58 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Projeto generated by hbm2java
 */
@Entity
@Table(name = "projeto", catalog = "scrum")
public class Projeto implements java.io.Serializable {

	private Integer idProjeto;
	private Equipe equipe;
	private String nome;
	private String descricao;
	private Date dataCriacao;
	private Set<Tarefa> tarefas = new HashSet<Tarefa>(0);
	private Set<Tarefa> tarefas_1 = new HashSet<Tarefa>(0);

	public Projeto() {
	}

	public Projeto(Equipe equipe, String nome) {
		this.equipe = equipe;
		this.nome = nome;
	}

	public Projeto(Equipe equipe, String nome, String descricao,
			Date dataCriacao, Set<Tarefa> tarefas, Set<Tarefa> tarefas_1) {
		this.equipe = equipe;
		this.nome = nome;
		this.descricao = descricao;
		this.dataCriacao = dataCriacao;
		this.tarefas = tarefas;
		this.tarefas_1 = tarefas_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_projeto", unique = true, nullable = false)
	public Integer getIdProjeto() {
		return this.idProjeto;
	}

	public void setIdProjeto(Integer idProjeto) {
		this.idProjeto = idProjeto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equipe", nullable = false)
	@NotNull
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@Column(name = "nome", nullable = false, length = 245)
	@NotNull
	@Length(max = 245)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao", length = 65535)
	@Length(max = 65535)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", length = 19)
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	public Set<Tarefa> getTarefas() {
		return this.tarefas;
	}

	public void setTarefas(Set<Tarefa> tarefas) {
		this.tarefas = tarefas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	public Set<Tarefa> getTarefas_1() {
		return this.tarefas_1;
	}

	public void setTarefas_1(Set<Tarefa> tarefas_1) {
		this.tarefas_1 = tarefas_1;
	}

}
