package org.domain.scrum.entity;

// Generated 12/04/2012 11:02:58 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Sprint generated by hbm2java
 */
@Entity
@Table(name = "sprint", catalog = "scrum")
public class Sprint implements java.io.Serializable {

	private Integer idSprint;
	private Equipe equipe;
	private String nome;
	private Date dataInicio;
	private Date dataFim;
	private Set<Tarefa> tarefas = new HashSet<Tarefa>(0);
	private Set<Tarefa> tarefas_1 = new HashSet<Tarefa>(0);

	public Sprint() {
	}

	public Sprint(Equipe equipe, String nome, Date dataInicio, Date dataFim) {
		this.equipe = equipe;
		this.nome = nome;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
	}

	public Sprint(Equipe equipe, String nome, Date dataInicio, Date dataFim,
			Set<Tarefa> tarefas, Set<Tarefa> tarefas_1) {
		this.equipe = equipe;
		this.nome = nome;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.tarefas = tarefas;
		this.tarefas_1 = tarefas_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_sprint", unique = true, nullable = false)
	public Integer getIdSprint() {
		return this.idSprint;
	}

	public void setIdSprint(Integer idSprint) {
		this.idSprint = idSprint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equipe", nullable = false)
	@NotNull
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@Column(name = "nome", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inicio", nullable = false, length = 19)
	@NotNull
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fim", nullable = false, length = 19)
	@NotNull
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sprint")
	public Set<Tarefa> getTarefas() {
		return this.tarefas;
	}

	public void setTarefas(Set<Tarefa> tarefas) {
		this.tarefas = tarefas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sprint")
	public Set<Tarefa> getTarefas_1() {
		return this.tarefas_1;
	}

	public void setTarefas_1(Set<Tarefa> tarefas_1) {
		this.tarefas_1 = tarefas_1;
	}

}
