package org.domain.scrum.entity;

// Generated 12/04/2012 11:02:58 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "scrum")
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private Equipe equipe;
	private String nome;
	private String login;
	private String senha;
	private String email;
	private Set<Tarefa> tarefas = new HashSet<Tarefa>(0);
	private Set<Tarefa> tarefas_1 = new HashSet<Tarefa>(0);

	public Usuario() {
	}

	public Usuario(Equipe equipe, String nome, String login, String senha,
			String email) {
		this.equipe = equipe;
		this.nome = nome;
		this.login = login;
		this.senha = senha;
		this.email = email;
	}

	public Usuario(Equipe equipe, String nome, String login, String senha,
			String email, Set<Tarefa> tarefas, Set<Tarefa> tarefas_1) {
		this.equipe = equipe;
		this.nome = nome;
		this.login = login;
		this.senha = senha;
		this.email = email;
		this.tarefas = tarefas;
		this.tarefas_1 = tarefas_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_usuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equipe", nullable = false)
	@NotNull
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@Column(name = "nome", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "login", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "senha", nullable = false, length = 32)
	@NotNull
	@Length(max = 32)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "email", nullable = false, length = 245)
	@NotNull
	@Length(max = 245)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Tarefa> getTarefas() {
		return this.tarefas;
	}

	public void setTarefas(Set<Tarefa> tarefas) {
		this.tarefas = tarefas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Tarefa> getTarefas_1() {
		return this.tarefas_1;
	}

	public void setTarefas_1(Set<Tarefa> tarefas_1) {
		this.tarefas_1 = tarefas_1;
	}

}
